#!/bin/bash

cd /bogo/gping

# note: ./www is sym linked to /var/www/html/gping (aka http://syswatch.science.mq.edu.au/gping/)

WEB=www
INCLUDE=$WEB/include.html
TIMESTAMP=$WEB/timestamp.html

source ~bogo/conda-setup.sh
conda activate gping
cat vmware-addresses |			# from PowerCLI (sitea, syd01m, syd04)
egrep -v -e "^10\.10\.100\.6" |		# firewall logs
egrep -v -e "^10\.10\.100\.7" |
egrep -v -e "^10\.10\.100\.26" |
egrep -v -e "^10\.10\.100\.129" |
egrep -v -e "^10\.111\." |		# survivor
egrep -v -e "^10\.123\." |		# survivor
egrep -v -e "^10\.138\." |		# HXC
egrep -v -e "^10\.63\." |		# SYD04 management VMs
egrep -v -e "^169\." |			# Network appliance VMs
egrep -v -e "^172\." |			# Private addresses
egrep -v -e "^192\." |			# Private addresses
egrep -v -e "^198\." |			# Network appliance VMs
egrep -v -e "MQU-MODE2" |		# SYD01 NSX appliances
egrep -v -e "MQUSYD01-DLR" |		# SYD01 NSX appliances
egrep -v -e "pbxvscm1001a" |            # PABX Appliances - never pingable ...
egrep -v -e "pbxvsamstr1001a" |
egrep -v -e "pbxvsutil1001a" |
egrep -v -e "pbxascms1001a" |
egrep -v -e "pbxvsamapp1002a" |
egrep -v -e "pbxasaes1001a" |
egrep -v -e "pbxvscm1002a" |
egrep -v -e "pbxvsrmsbc1001a" |
egrep -v -e "pbxvsesmgr1001a" |
egrep -v -e "pbxvssmgr1001a" |
egrep -v -e "pbxvsaams1001b" |
egrep -v -e "pbxvscmess1001b" |
egrep -v -e "pbxvsdiag1001b" |
egrep -v -e "pbxvsesmgr1001b" |
egrep -v -e "pbxvsutil1001b" |
egrep -v -e "pbxvsrmsbc1001a" |
egrep -v -e "pbxvsrmsbc1001a" |
egrep -v -e "pbxvsaams1001a" |
egrep -v -e "pbxvssbcm1001a" |
egrep -v -e "xmc-nac" |			# Extreme Networks applicances
egrep -v -e "xmc-purview" |
egrep -v -e "dcaasprd2002a" |		# Snowflake
egrep -v -e "dcaasuat2002" |
python gping.py |
sort -n |
awk -F, '
  BEGIN { colour["True"]="green"; colour["False"] = "red"; } 
        { print "<div id=\"" $1 "," $3 "," $4 "\" class=\"indicator " colour[$2] "\"><span class=\"tooltiptext\">" $1 "<br>" $3 "<br>" $4"</span></div>"}
' > $INCLUDE
chmod a+r $INCLUDE

date > $TIMESTAMP
