#!/bin/bash
#
# RJM - Fri 17 Feb 15:06:51 AEDT 2023

cd $(dirname $0)

ALERT="red-alert.ALERT"
RE_ALERT=$((60*60*24))		# seconds between alerts for same ALERTage

TEAMSWEBHOOK=https://mqoutlook.webhook.office.com/webhookb2/f39b181d-cb63-4b34-94a4-f5ad588cea70@82c514c1-a717-4087-be06-d40d2070ad52/IncomingWebhook/53de3975bd1f4ca6a84a1a5b44b8ed78/61bd2389-68e6-440d-ae24-a726d47712f7

CURL="curl"
colour="red"

GPING="(http://syswatch.science.mq.edu.au/gping/)"

# Assume the best
STATUS=GREEN

if grep -q "indicator ${colour}" www/include.html; then

  #echo RED
  STATUS=RED
  HOSTS=$(grep "indicator ${colour}" www/include.html | sed 's/<[^>]*>/ /g')
  #echo $HOSTS

fi
 


if [ "$STATUS" == "GREEN" ]; then

  if [ -f ${ALERT} ]; then
    echo no longer any ALERT
    exit
    echo ${CURL} \
      -silent \
      -X POST \
      -H "Content-Type:application/json"  \
      -d "{\"text\": \"${STATUS}: ${GPING}\"}" \
      $TEAMSWEBHOOK > /dev/null
    rm ${ALERT}
  fi

else

  # remove ${ALERT} if older than RE-ALERT time
  if [ -f ${ALERT} ] && [ $(( (`date +%s` - `stat -L --format %Y ${ALERT}`) )) -gt ${RE_ALERT} ] ; then
    #echo re-alert
    rm ${ALERT}
  fi
    
  # send alert - when either the ALERT file doen't ready exit OR the ALERT file contents is different from current HOST list
  if [ ! -f ${ALERT} ] || ! diff ${ALERT}  <(echo ${HOSTS}) > /dev/null; then

    #echo Founds some RED hosts - let TEAMS know ...
    ${CURL} \
      -silent -X POST \
      -H "Content-Type:application/json"  \
      -d "{\"text\": \"${STATUS}-ALERT: ${GPING} <br><br> ${HOSTS}\"}" \
      $TEAMSWEBHOOK > /dev/null
    echo $HOSTS > ${ALERT}

  fi
fi
